<a href="https://colab.research.google.com/github/Giry0316/OMock-/blob/master/5_14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
a = 365
print("일년은 ",a,"일 입니다")



일년은  365 일 입니다


In [14]:
c = 10

b = a+ c

b

375

In [16]:
a0 = 1
a1 = 2
a2 = 3
print(a0, a1, a2)
print("a = %d" % a)

1 2 3
a = 365


In [22]:
a = [1, 2, 3] #a는 배열

print(a)

[1, 2, 3]
1 2 3


In [ ]:
#배열 원소를 가리킬 떄
print(a[0]) 

print(a[0], a[1], a[2])

print(a[0])
print(a[1])
print(a[2])

# i = a[0]

for i in a :
  print(i);
  

In [49]:
arr = [[1,2,3],
       [4,5,6],
       [7,8,9]]

print(arr)

print(arr[0], arr[1])
print(arr[0][0], arr[0][1], arr[0][2], 
      arr[1][0], arr[1][1], arr[1][2], 
      arr[2][0], arr[2][1], arr[2][2], )

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[1, 2, 3] [4, 5, 6]
1 2 3 4 5 6 7 8 9


In [54]:
for row in arr:
  for col in row:
    print(col)

1
2
3
4
5
6
7
8
9


In [62]:
import numpy as np
anp = np.array(a)
print(anp)
anp

[1 2 3]


array([1, 2, 3])

In [ ]:
anp[0]

In [66]:
anp2 = np.array(arr)


In [68]:
anp2[0,2]

3

In [72]:
vec = np.arange(10) #0에서 출발해서 n-1값으로 끝남 
vec


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
vec2 = np.arange(3, 10) #n1값에서 시작해서 n2 - 1값까지 출력
vec2

array([3, 4, 5, 6, 7, 8, 9])

In [77]:
vec3 = np.arange(3,10,2)#n1값에서 시작해서 n3 간격으로 n2 - 1값까지 출력
vec3


array([3, 5, 7, 9])

In [83]:
np.arange(10,2, -1) #n1값이 n2보다 클때(n1 > n2) n1값에서부터 n2값까지 n3만큼 감소 (이때 n3를 적어야하고, n3는 음수여야함)

array([10,  9,  8,  7,  6,  5,  4,  3])

In [97]:
#백터 크기 계산
v = np.arange(3,5)# v값 정의
vsquare = np.square(v)# v값 제곱
vsum = np.sum(vsquare)# vsquare값 총합
vroot = np.sqrt(vsum)# vsum 루트
vroot

5.0

In [100]:
#square, sum, sqrt를 한꺼번에 계산하는 방법
#두개의 자료(밑변, 높이)에 한하여 가능
np.hypot(v[0], v[1])

5.0

In [102]:
# 두 개 이상의 자료에도 계산하는 명령어
np.linalg.norm(v)

5.0

In [111]:
#단위 벡터
e1 = np.array([1,0,0])

np.linalg.norm(e1)

1.0

In [112]:
e2 = np.array([0,1,0])

np.linalg.norm(e2)

1.0

In [115]:
e3 = np.array([0,0,1])

np.linalg.norm(e3)

1.0

In [120]:
v_3 = np.array([1,2,3])
v_3n = np.linalg.norm(v_3)

In [122]:
#단위 벡터를 구한값
v_3u = v_3 / v_3n
v_3u

array([0.26726124, 0.53452248, 0.80178373])